"""Add vector column for embeddings

Revision ID: 13e351523117
Revises: ee7f189dc501
Create Date: 2025-07-25 11:12:05.073498

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '13e351523117'
down_revision = 'ee7f189dc501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', Vector(1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
